### ISSUE TITLE
Docus currently broken

### ISSUE THREAD

**Issue by justindasilva** [nuxt-themes/docus#681]
I just tried creating a fresh Docus project using the command on the website:
```
npx nuxi init docs -t themes/docus
```

It seems when I `yarn dev`, the localhost will just hang and nothing will show up.

I've always wondered about Nuxt, is there a way to run `yarn dev --verbose` or `yarn dev -vvv` to see a bit more about what might be going wrong?

**Comment by zoey-kaiser** [comment]
I have the same issue as well. I used to only struggle with #680, but after a day of programming (lots of hot reloads, restarts etc.) Docus, even with a brand new scaffold is failing to start. 

I have waited 10+ minutes for it to load and nothing happens. I do not get an error thrown. Therefore the only logs I have are:

```
Nuxi 3.0.0 
Nuxt 3.0.0 with Nitro 1.0.0 
✔ Using Nuxt Typography v0.0.13 

  > Local:    http://localhost:3000/ 
  > Network:  http://192.168.0.232:3000/
  > Network:  http://[2a02:1810:cc2e:a300:187d:17d2:d8f8:4249]:3000/
  > Network:  http://[2a02:1810:cc2e:a300:6194:fbdc:35e7:cd5f]:3000/

ℹ Vite client warmed up in 78064ms 
✔ Nitro built in 1191 ms
```

78 seconds already seems pretty long for vite to load (sometimes it is even longer). 

Environment:
```
- Operating System: `Darwin`
- Node Version:     `v16.17.0`
- Nuxt Version:     `3.0.0`
- Nitro Version:    `1.0.0`
- Package Manager:  `yarn@1.22.11`
- Builder:          `vite`
- User Config:      `extends`
- Runtime Modules:  `-`
- Build Modules:    `-`
```

I am also using a M1 mac (IDK if that changes anything, but I have had it that it would react differently).

Other Nuxt3 projects are still running fine for me. Is there anything that might be specific to our machines that prevent vite from rendering docus properly? If you need any other information about my hardware or setup, I would be happy to provide it! Maybe there is something we should reinstall that might be broken internally on my setup?

Thank you to any help in advance!

**Comment by sfxcode** [comment]
Same Problem for me on an Intel Mac i9 on 12.6.1 Monterey.  Vite warmup takes minutes ... nothing happens in browser.

**Comment by bdrtsky** [comment]
Probably related https://github.com/nuxt-themes/docus/issues/672

**Comment by geyermichael** [comment]
The same problem occurred for me when I run `npx nuxi@latest init docs -t themes/docus` install packages and run `npm run dev`.

It works, but it took about 5 minutes until I could see the application under localhost:3000.

**Comment by KyleRicardo** [comment]
Idk if it's broken. But I followed the official "Getting Started" guide and I got this error prompt. I'm new to nuxt and this is a blow to my confidence in nuxt. I'm on Windows with latest node.js npm and pnpm.
![image](https://user-images.githubusercontent.com/10452272/202987543-73aa6812-8e92-410c-9443-c25e33306831.png)

**Comment by ipatate** [comment]
Same, very slow on start for local dev and build. The deploy on Netlify take 13mn 😵 ! https://presswind-doc.wp-performance.com/

<img width="778" alt="Screenshot 2022-11-21 at 09 32 57" src="https://user-images.githubusercontent.com/46760/203002968-a8eae08e-6ab4-4f98-84db-d8303da5d2f4.png">

**Comment by Tahul** [comment]
Hello here,

Thank you all for reporting this issue.

I will try to solve it by today, this is extreme priority.

**Comment by zoey-kaiser** [comment]
> Idk if it's broken. But I followed the official "Getting Started" guide and I got this error prompt. I'm new to nuxt and this is a blow to my confidence in nuxt. I'm on Windows with latest node.js npm and pnpm. 

This issue reminds me a lot of an issue we had in our module `nuxt-session`. AFAIK Windows parses URL structures differently then mac and linux. This can lead to issues like the one you showed above. 

Here is our issue and PR where we fixed these issues for nuxt-session:

https://github.com/sidebase/nuxt-session/issues/12
https://github.com/sidebase/nuxt-session/pull/13

**Comment by MrSociety404** [comment]
> Hello here,
> 
> Thank you all for reporting this issue.
> 
> I will try to solve it by today, this is extreme priority.

If it can help, this issue was fixed recently in nuxt/i18n for nuxt3 just here https://github.com/nuxt-community/i18n-module/issues/1518

**Comment by KyleRicardo** [comment]
> AFAIK Windows parses URL structures differently then mac and linux. This can lead to issues like the one you showed above.

Never came across a framework that cannot be used out-of-the-box. Vue ecosystem frameworks are usually very easy to get started smoothly. This frustrating error even let me ignore the pretty long vite warming up time. I'm a little speechless. Did official even run `npm run dev` on Windows before release?

**Comment by Tahul** [comment]
Hey :)

I just published 0.3.2, could you guys try this version and keep me up to date if it solves your issue?

Please be cautious with reinstalling your dependencies with that new version.

I think we are tracking down two different issues here, so it might not work for all of you, but it's a first step.

Thank you again for your feedback.

**Comment by zoey-kaiser** [comment]
> Hey :)
> 
> I just published 0.3.2, could you try this version and keep me up to date if it solves your issue?
> 
> Please be cautious with reinstalling your dependencies with that new version.
> 
> I think we are tracking down two different issues here, so it might not work for all of you, but it's a first step.
> 
> Thank you again for your feedback.

Hi @Tahul! I just upgraded my docs and it did the trick!

Thank you for the quick response time ❤️

**Comment by bennyzen** [comment]
Yep, you fixed it. Thanks a lot.

**Comment by ipatate** [comment]
yep, fixed, thanks !!
![Screenshot 2022-11-21 at 17 31 21](https://user-images.githubusercontent.com/46760/203108950-83c7624d-f04f-48b1-951f-cd6248b4f7cf.png)

**Comment by grbd** [comment]
> @KyleRicardo ; could you tell me if this update solved your problem as well?
> 
> If not, could we start tracking that inside another issue?

I've just tried this myself and I'm afraid 0.3.2 doesn't appear to fix the windows pathing issue
I would like to say thanks very much for finally doing a public release though I've taken an interest in this for a while but the only source I've had access to has been via npmjs

Issue raised here - https://github.com/nuxt-themes/docus/issues/684

**Comment by sfxcode** [comment]
Fixed my problem, thank you !

**Comment by monsat** [comment]
Fixed, thank you.

In my case, I removed all `node_modules/` in my monorepo.

**Comment by Tahul** [comment]
@KyleRicardo ; we are now tracking in #684

As others has marked the original issue as resolved, I prefer to close this one and keep conversations in proper issue!

Thanks again for your feedback, and see you on #684 to resolve this one! :)

**Comment by sfxcode** [comment]
@Tahul Same problem like this after updating to version 1.0.1.
Startup does not come to proper end in time and processor load is rising ....

**Comment by Tahul** [comment]
Hey @sfxcode ; could you try regenerating your lockfile ?

Reinstall all dependencies to grab Pinceau ^0.7.1.

I'm sorry, I think latest release I made rollbacked the fixed I push for this issue.

It should be fine now.

**Comment by sfxcode** [comment]
Hi @Tahul, worked like a a charm. Sorry to interrupt at sunday ...
